### ISSUE TITLE
seminar per day is being set to None

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#432]
traceback:
```
Exception on /edit/schedule/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sage/sage-9.0/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mathseminars/seminars-git-live/seminars/users/main.py", line 154, in decorated_view
    return fn(*args, **kwargs)
  File "/home/mathseminars/seminars-git-live/seminars/create/main.py", line 875, in edit_seminar_schedule
    schedule = layout_schedule(seminar, data)
  File "/home/mathseminars/seminars-git-live/seminars/create/main.py", line 816, in layout_schedule
    newslots += [(seminar.show_schedule_date(d), "", None) for i in range(seminar.per_day)]
TypeError: 'NoneType' object cannot be interpreted as an integer
[2020-05-07 02:33:55 UTC] 500 error on URL https://researchseminars.org/edit/schedule/?shortname=Zoomplitudes2020 ("'NoneType' object cannot be interpreted as an integer",)
```

**Comment by roed314** [comment]
Resolved; fix pushed to live.
